### ISSUE TITLE
Unable to authenticate from Travis

### ISSUE THREAD

**Issue by cboettig** [Sija/garb#33]
Authentication works just fine following your README when I use your gem locally, but authentication fails when I attempt to deploy from Travis CI.  The key, username, and password are correct but for some reason Google detects this as a possible intrusion and blocks access anyway.  Following Google's directions about logging in and permitting access through my local machine doesn't help.  

Have you seen this done or have any idea how to handle this case? I've encrypted my API key, username, password, etc with the standard travis mechanism and verified that they are interpreted correctly on travis CI.  Perhaps Google just wants to prevent this kind of access?  

My ruby script is [here](https://github.com/cboettig/labnotebook/blob/5798eb8af6b6c016d6525f3dea9f89f88be0ff45/_plugins/jekyll-labnotebook-plugins/google_analytics.rb), as a jekyll plugin. Thanks for your help or any suggestions on how to work around this!

**Comment by Sija** [comment]
Closing, since I don't think it's still relevant after ~8yrs with no followup, in any case feel free to reopen.
