### ISSUE TITLE
Unable to Login with Single User - Garb::AuthenticationRequest::AuthError

### ISSUE THREAD

**Issue by alokswain** [Sija/garb#39]
I am on the 0.9.1 version of the gem and I have disabled 2-Step Verification. I checked the gem files and api_key isnt isnt a attribute for Garb::Session in version(I think its only needed if I have 2-Step verification enabled). Can you please let me know what am I missing.
```
Garb::Session.login("<my email>", "<mypwd>")
```
returns Garb::AuthenticationRequest::AuthError, below is the log
```
Garb::AuthenticationRequest::AuthError: Garb::AuthenticationRequest::AuthError
	from /home/alok/.rvm/gems/ruby-1.9.3-p385/gems/garb-0.9.1/lib/garb/authentication_request.rb:37:in `block in send_request'
	from /home/alok/.rvm/rubies/ruby-1.9.3-p385/lib/ruby/1.9.1/net/http.rb:1322:in `block (2 levels) in transport_request'
	from /home/alok/.rvm/rubies/ruby-1.9.3-p385/lib/ruby/1.9.1/net/http.rb:2671:in `reading_body'
	from /home/alok/.rvm/rubies/ruby-1.9.3-p385/lib/ruby/1.9.1/net/http.rb:1321:in `block in transport_request'
	from /home/alok/.rvm/rubies/ruby-1.9.3-p385/lib/ruby/1.9.1/net/http.rb:1316:in `catch'
	from /home/alok/.rvm/rubies/ruby-1.9.3-p385/lib/ruby/1.9.1/net/http.rb:1316:in `transport_request'
	from /home/alok/.rvm/rubies/ruby-1.9.3-p385/lib/ruby/1.9.1/net/http.rb:1293:in `request'
	from /home/alok/.rvm/gems/ruby-1.9.3-p385/gems/rest-client-1.6.7/lib/restclient/net_http_ext.rb:51:in `request'
	from /home/alok/.rvm/rubies/ruby-1.9.3-p385/lib/ruby/1.9.1/net/http.rb:1286:in `block in request'
	from /home/alok/.rvm/rubies/ruby-1.9.3-p385/lib/ruby/1.9.1/net/http.rb:745:in `start'
	from /home/alok/.rvm/rubies/ruby-1.9.3-p385/lib/ruby/1.9.1/net/http.rb:1284:in `request'
	from /home/alok/.rvm/gems/ruby-1.9.3-p385/gems/rest-client-1.6.7/lib/restclient/net_http_ext.rb:51:in `request'
	from /home/alok/.rvm/gems/ruby-1.9.3-p385/gems/garb-0.9.1/lib/garb/authentication_request.rb:36:in `send_request'
	from /home/alok/.rvm/gems/ruby-1.9.3-p385/gems/garb-0.9.1/lib/garb/authentication_request.rb:49:in `auth_token'
	from /home/alok/.rvm/gems/ruby-1.9.3-p385/gems/garb-0.9.1/lib/garb/session.rb:10:in `login'
	from (irb):12
	from /home/alok/.rvm/gems/ruby-1.9.3-p385/gems/railties-3.2.19/lib/rails/commands/console.rb:47:in `start'
	from /home/alok/.rvm/gems/ruby-1.9.3-p385/gems/railties-3.2.19/lib/rails/commands/console.rb:8:in `start'
	from /home/alok/.rvm/gems/ruby-1.9.3-p385/gems/railties-3.2.19/lib/rails/commands.rb:41:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'irb(main):013:0>
```

**Comment by YasuakiOmokawa** [comment]
google allows only oauth2.0 . Please change it.

2015-06-02 16:58 GMT+09:00 Alok Swain <notifications@github.com>:

> I am on the 0.9.1 version of the gem and my account doesnt have 2 FA
> enabled. I checked the gem files and api_key isnt isnt a attribute for this
> version. Can you let me know what am I missing.
> Please find the logs below.
>
> Garb::Session.login("<my email>", "<mypwd>")
>
> returns Garb::AuthenticationRequest::AuthError, below is the log
>
> Garb::AuthenticationRequest::AuthError: Garb::AuthenticationRequest::AuthError
>     from /home/alok/.rvm/gems/ruby-1.9.3-p385/gems/garb-0.9.1/lib/garb/authentication_request.rb:37:in `block in send_request'
>     from /home/alok/.rvm/rubies/ruby-1.9.3-p385/lib/ruby/1.9.1/net/http.rb:1322:in `block (2 levels) in transport_request'
>     from /home/alok/.rvm/rubies/ruby-1.9.3-p385/lib/ruby/1.9.1/net/http.rb:2671:in `reading_body'
>     from /home/alok/.rvm/rubies/ruby-1.9.3-p385/lib/ruby/1.9.1/net/http.rb:1321:in `block in transport_request'
>     from /home/alok/.rvm/rubies/ruby-1.9.3-p385/lib/ruby/1.9.1/net/http.rb:1316:in `catch'
>     from /home/alok/.rvm/rubies/ruby-1.9.3-p385/lib/ruby/1.9.1/net/http.rb:1316:in `transport_request'
>     from /home/alok/.rvm/rubies/ruby-1.9.3-p385/lib/ruby/1.9.1/net/http.rb:1293:in `request'
>     from /home/alok/.rvm/gems/ruby-1.9.3-p385/gems/rest-client-1.6.7/lib/restclient/net_http_ext.rb:51:in `request'
>     from /home/alok/.rvm/rubies/ruby-1.9.3-p385/lib/ruby/1.9.1/net/http.rb:1286:in `block in request'
>     from /home/alok/.rvm/rubies/ruby-1.9.3-p385/lib/ruby/1.9.1/net/http.rb:745:in `start'
>     from /home/alok/.rvm/rubies/ruby-1.9.3-p385/lib/ruby/1.9.1/net/http.rb:1284:in `request'
>     from /home/alok/.rvm/gems/ruby-1.9.3-p385/gems/rest-client-1.6.7/lib/restclient/net_http_ext.rb:51:in `request'
>     from /home/alok/.rvm/gems/ruby-1.9.3-p385/gems/garb-0.9.1/lib/garb/authentication_request.rb:36:in `send_request'
>     from /home/alok/.rvm/gems/ruby-1.9.3-p385/gems/garb-0.9.1/lib/garb/authentication_request.rb:49:in `auth_token'
>     from /home/alok/.rvm/gems/ruby-1.9.3-p385/gems/garb-0.9.1/lib/garb/session.rb:10:in `login'
>     from (irb):12
>     from /home/alok/.rvm/gems/ruby-1.9.3-p385/gems/railties-3.2.19/lib/rails/commands/console.rb:47:in `start'
>     from /home/alok/.rvm/gems/ruby-1.9.3-p385/gems/railties-3.2.19/lib/rails/commands/console.rb:8:in `start'
>     from /home/alok/.rvm/gems/ruby-1.9.3-p385/gems/railties-3.2.19/lib/rails/commands.rb:41:in `<top (required)>'
>     from script/rails:6:in `require'
>     from script/rails:6:in `<main>'irb(main):013:0>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Sija/garb/issues/39>.
>



-- 
┏◇─────────────────
┌─╂ 株式会社 先駈
■━┛ 代表取締役
│ 面川 泰明
│ TEL 03-6271-6858 FAX 03-6850-7117
│ Mail : omokawa@senk-inc.co.jp
□────────────────────

**Comment by alokswain** [comment]
Thanks. Closing the Issue.
