### ISSUE TITLE
After the OAuth 1.o shutdown on April 20, 2015 the Garb authentication is not working

### ISSUE THREAD

**Issue by ankitsuhail** [Sija/garb#43]
As the updated readme says that the ClientLogin, AuthSub and OAuth 1.0 shutdown scheduled for April 20, 2015. The password and the username is correct.The Garb is now unable to authenticate to the servers of google. This is what I get 
when I execute the command :

> Garb::Session.login('username@gmail.com', 'password')

Garb::Request::Authentication::AuthError: Garb::Request::Authentication::AuthError 
from c:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/bundler/gems/garb-86e1bc667477/lib/garb/request/authentication.rb:39:in `block in send_request'

Are there any workarounds?

**Comment by Sija** [comment]
Yep, using OAuth2 works as intended.
